version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - java -version
      - echo Building spring project...
      - ./gradlew build
      - echo Building docker image...
      - docker build -t gmdb/monolith:0.1 .
      - docker tag gmdb/monolith:0.1 159757098416.dkr.ecr.us-west-1.amazonaws.com/gmdb/monolith
  post_build:
    commands:
      - echo Build complete on `date`
      - echo Pushing the Docker image...
      - docker push
      - docker push 159757098416.dkr.ecr.us-west-1.amazonaws.com/gmdb/monolith/$IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
  files:
    - build/libs/gmdb-mono.lith-0.0.1-SNAPSHOT.jar