version: 0.2

  phases:
    install:
      commands:
        - echo Nothing to do in the insall phase...
    pre_build:
      commands:
        - echo Nothing to do int the pre_build phase...
    build:
      commands:
        - echo Build started on `date`
        - gradlew build
    post_build:
      commands:
        - echo Build complete on `date`
        - echo creating the docker image
        - docker build -t gmdb/monolith:0.1 .
    artifacts:
      files:
        - build/libs/gmdb-monolith-0.0.1-SNAPSHOT.jar
